"""Initial migration

Revision ID: 68495ef94996
Revises: 
Create Date: 2025-05-24 23:43:56.260430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68495ef94996'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
